// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Concrete.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            Name = "Author 1"
                        },
                        new
                        {
                            Id = new Guid("a8305503-a8da-4830-bcec-fa985e594a90"),
                            Name = "Author 2"
                        },
                        new
                        {
                            Id = new Guid("503939b1-a170-4474-aa31-f89f5c878bbb"),
                            Name = "Author 3"
                        });
                });

            modelBuilder.Entity("Models.Entities.Concrete.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BorrowedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84c52f0a-401d-40d2-80a1-281e48d5c17e"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            BorrowedBy = "ONUR DERMAN",
                            ISBN = "800929a7",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = false,
                            Name = "Book 1",
                            ReturnDate = new DateTimeOffset(new DateTime(2024, 1, 7, 0, 13, 27, 522, DateTimeKind.Unspecified).AddTicks(4800), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("db63310e-3ddc-4715-a9cd-1f0cf4b14a59"),
                            AuthorId = new Guid("a8305503-a8da-4830-bcec-fa985e594a90"),
                            ISBN = "8d95fddd",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 2"
                        },
                        new
                        {
                            Id = new Guid("5c3a0e12-2bc9-45e1-abb3-c3201c94295e"),
                            AuthorId = new Guid("503939b1-a170-4474-aa31-f89f5c878bbb"),
                            BorrowedBy = "ONUR DERMAN",
                            ISBN = "38bca0d5",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = false,
                            Name = "Book 3",
                            ReturnDate = new DateTimeOffset(new DateTime(2023, 12, 24, 0, 13, 27, 522, DateTimeKind.Unspecified).AddTicks(4886), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b64f2fee-3829-4b9b-af12-bfee40fde344"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            ISBN = "c896cee0",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 4"
                        },
                        new
                        {
                            Id = new Guid("765d0dac-fe8c-447d-a238-f2d941a919aa"),
                            AuthorId = new Guid("a8305503-a8da-4830-bcec-fa985e594a90"),
                            ISBN = "d91e3a2b",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 5"
                        },
                        new
                        {
                            Id = new Guid("7f039958-66fc-4b1a-9234-a3775c00cbe6"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            ISBN = "3326075a",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 6"
                        },
                        new
                        {
                            Id = new Guid("f95b5bbe-daa9-4b45-9db7-dfff0126d384"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            ISBN = "fdd6be84",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 7"
                        },
                        new
                        {
                            Id = new Guid("442daaec-0a77-48b2-b236-140fd3636cdb"),
                            AuthorId = new Guid("a8305503-a8da-4830-bcec-fa985e594a90"),
                            ISBN = "1b6caaed",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 8"
                        },
                        new
                        {
                            Id = new Guid("094ada91-108c-42d2-876b-a982db803495"),
                            AuthorId = new Guid("503939b1-a170-4474-aa31-f89f5c878bbb"),
                            ISBN = "d5ab77cf",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 9"
                        },
                        new
                        {
                            Id = new Guid("444e0e9b-51ce-4776-ab84-0031ae083cc4"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            ISBN = "e43f0a42",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 10"
                        },
                        new
                        {
                            Id = new Guid("517c37bb-720c-48d5-8e26-8d2ed1e3933a"),
                            AuthorId = new Guid("a8305503-a8da-4830-bcec-fa985e594a90"),
                            BorrowedBy = "ONUR DERMAN",
                            ISBN = "f1589a02",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = false,
                            Name = "Book 11",
                            ReturnDate = new DateTimeOffset(new DateTime(2024, 1, 3, 0, 13, 27, 522, DateTimeKind.Unspecified).AddTicks(4939), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3c042ca7-6ebc-4e8c-80c0-cd65f7ebc021"),
                            AuthorId = new Guid("e5d7b08b-6c9c-4dbb-99f5-cfe1befa9659"),
                            ISBN = "c6a02dc6",
                            ImageUrl = "images\\book\\default.jpg",
                            IsAvailable = true,
                            Name = "Book 12"
                        });
                });

            modelBuilder.Entity("Models.Entities.Concrete.Book", b =>
                {
                    b.HasOne("Models.Entities.Concrete.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Models.Entities.Concrete.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
